---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: virtmerlin/c0-worker
inputs:
  - name: aws-concourse
  - name: pcfawsops-terraform-state-get
  - name: tool-om
run:
  path: aws-concourse/scripts/config-director.sh
